### ISSUE TITLE
Compilation Error:Ö Multiple definitions of 

### ISSUE THREAD

**Issue by alexloose** [AK-Homberger/D1Mini-GasCounter#3]
Hi AK-Homberger, Teams,

I do get the following compilation error message:

`
C:\Users\XXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/time.cpp:28: multiple definition of `_Z12getLocalTimeP2tmj'; C:\Users\XXX\AppData\Local\Temp\arduino\sketches\AE7AE1529F0AC61DE62B2B28D03E0C2B\sketch\Gascounter.ino.cpp.o:C:\Users\alo\Downloads\D1Mini-GasCounter-main\Gascounter/Gascounter.ino:294: first defined here
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1
`

This was solved by renaming the funtion getLocalTime to something else, e.g. getLocalTimeXXX and change all their references in code.

regards, Alexander

**Comment by dervolki** [comment]
Hello, 
I face exactly the same issue. 
IDE is 
Version: 2.1.0
Date: 2023-04-17T11:52:02.744Z
CLI Version: 0.32.2
Host is a M2MacBookPro
Os up to date. 
Brew up to date.  
URL: https://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by dervolki** [comment]
quick update:

installed old IDE 
IDE: 1.8.19
Same board URL. 


result in the same error

`/Users/volker/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.1.0-gcc10.3-e5f9fec/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /var/folders/8k/p_4lnp0s08334wxf6fvhwwvm0000gn/T/arduino_cache_836220/core/core_c48fcb446ccceeddd4e2a94e9818c5d5.a(time.cpp.o): in function `_Z12getLocalTimeP2tmj':
/Users/volker/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/cores/esp8266/time.cpp:28: multiple definition of `_Z12getLocalTimeP2tmj'; sketch/Gascounter.ino.cpp.o:/Users/volker/D1Mini-GasCounter/Gascounter/Gascounter.ino:294: first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.`

**Comment by dervolki** [comment]
Hello, 
I dowloaded Yesterday and apperently this worked fine for me. 
Thanks a  lot for your help

**Comment by alexloose** [comment]
Hi,
that's also what I did. works for me
