### ISSUE TITLE
Compilation error: 'configTzTime' was not declared in this scope

### ISSUE THREAD

**Issue by zlBomBkU** [AK-Homberger/D1Mini-GasCounter#8]
Hi, 
I get this error message during compilation with Arduino 2.1.1

"_/Users/name/Downloads/D1Mini-GasCounter-main-2/Gascounter/Gascounter.ino: In function 'void setup()':
/Users/name/Downloads/D1Mini-GasCounter-main-2/Gascounter/Gascounter.ino:140:35: error: 'configTzTime' was not declared in this scope
   configTzTime(TZ_INFO, NTP_SERVER);    // Synchronise system time with NTP
                                   ^

exit status 1

Compilation error: 'configTzTime' was not declared in this scope_"

What to do?

Any hints?

Thanks a lot.

**Comment by AK-Homberger** [comment]
Code is created/tested with IDE 2.1.0. No compilation errors with this version.
